# -*- make -*-
BASE=../..
SUBDIR=doc/pl

# Bring in the default rules
include ../../buildlib/defaults.mak

# Debian Doc SGML Documents
SOURCE = offline.pl.sgml
DEBIANDOC_HTML_OPTIONS=-l pl
include $(DEBIANDOC_H)
