#!/bin/bash
LD_LIBRARY_PATH=./build/bin ./build/bin/apt-get -o Dir=/home/ishan/devel/apt/my/experiments/workingdir/rootdir -o Dir::Bin::methods=./build/bin/methods -o Dir::State::status=/home/ishan/devel/apt/my/experiments/workingdir/rootdir/var/lib/dpkg/status -o Dir::Bin::dpkg=fakeroot $*
