#!/bin/sh

if [ $1 = "http://www.debian.org:90/temp/test" ]; then
    echo "http://example.com"
fi
if [ $1 = "http://www.debian.org:91/temp/test" ]; then
    echo "This works" >&2
    echo "http://example.com/foo"
fi
