# -*- make -*-
BASE=..
SUBDIR=cmdline

# Bring in the default rules
include ../buildlib/defaults.mak

# The library name
PROGRAM=apt-cache
SLIBS = -lapt-pkg 

# Source code for the contributed non-core things
SOURCE = apt-cache.cc

include $(PROGRAM_H)
