# -*- make -*-
BASE=../..
SUBDIR=doc/fr

# Bring in the default rules
include ../../buildlib/defaults.mak

SOURCE = apt-cdrom.fr.8 apt-config.fr.8 apt-extracttemplates.fr.1 \
         apt-ftparchive.fr.1 apt-sortpkgs.fr.1 apt.conf.fr.5 \
         apt_preferences.fr.5
INCLUDES = apt.ent.fr
include $(SGML_MANPAGE_H)
