# -*- make -*-
BASE=../..
SUBDIR=doc/fr

# Bring in the default rules
include ../../buildlib/defaults.mak

# Man pages
SOURCE = apt-cache.fr.8 apt-get.fr.8 apt-cdrom.fr.8 apt.conf.fr.5 \
         sources.list.fr.5 apt-config.fr.8 apt-sortpkgs.fr.1 \
	 apt-ftparchive.fr.1 apt_preferences.fr.5 apt-extracttemplates.fr.1 \
	 vendors.list.fr.5
INCLUDES = apt.ent.fr
include $(SGML_MANPAGE_H)
