# -*- make -*-
BASE=../..
SUBDIR=doc/es

# Bring in the default rules
include ../../buildlib/defaults.mak

# Man pages
SOURCE = apt-cache.es.8 apt-get.es.8 apt-cdrom.es.8 apt.conf.es.5 \
         sources.list.es.5 apt-config.es.8 apt_preferences.es.5
INCLUDES = apt.ent.es
include $(SGML_MANPAGE_H)
