#!/bin/sh

NAMES="`sed -ne 's/'\''/'\''\\\\'\'''\''/g;
	         s/^.*CVS:\([^ ]\+\) \([^<]\+\) <\([^>]*\)>/\
		    -u '\''\1:\2:\3'\''/gp' AUTHORS`"
OPTIONS="-l 78"

# Generate the standard ChangeLog
echo CVSIGNORE=po rcs2log $OPTIONS $NAMES
eval CVSIGNORE=po rcs2log $OPTIONS $NAMES >> ChangeLog

# Generate the po ChangeLog
#echo rcs2log $OPTIONS $NAMES po
#eval rcs2log $OPTIONS $NAMES po >> po/ChangeLog
