debian/*.service /lib/systemd/system/
debian/*.timer /lib/systemd/system/
debian/apt.systemd.daily usr/lib/apt
etc/apt/
usr/bin/apt
usr/bin/apt-cache
usr/bin/apt-cdrom
usr/bin/apt-config
usr/bin/apt-get
usr/bin/apt-key
usr/bin/apt-mark
usr/lib/*/libapt-private.so*
usr/lib/apt/apt-helper
usr/lib/apt/methods/
usr/lib/apt/planners/dump
usr/lib/apt/solvers/dump
usr/lib/dpkg/methods/apt/
usr/share/bash-completion/completions/
usr/share/locale/*/*/apt.mo
var/
