#! /bin/sh

# apt postinst, based liberally on James Troup's gpm postinst
# Copyright (C) 1998, Ben Gertzfield <che@debian.org>

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

set -e

create_apt_conf ()
{
 EXAMPLE_SOURCE=/usr/share/doc/apt/examples/sources.list
 if [ -f $EXAMPLE_SOURCE ]; then
     cp $EXAMPLE_SOURCE /etc/apt/sources.list
 fi
}
 
check_apt_conf ()
{
 true
 # this is for future expansion
}

#DEBHELPER#

case "$1" in
       configure)
	       #
               # If there is no /etc/apt/sources.list then create a default
	       #
	       if [ ! -f /etc/apt/sources.list ]; then
	         create_apt_conf
	       else
	         check_apt_conf
	       fi
esac
