#! /bin/sh

# apt postrm
# Copyright (C) 1998, Ben Gertzfield <che@debian.org>

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

set -e

#DEBHELPER#

dpkg-maintscript-helper rm_conffile /etc/apt/apt.conf.d/01ubuntu \
	0.8.16~exp12ubuntu6 -- "$@"

case "$1" in
       remove)
		;;
       purge)
		rm -rf /var/cache/apt
		rm -rf /var/lib/apt
esac

