# -*- make -*-
BASE=..
SUBDIR=dselect

# Bring in the default rules
include ../buildlib/defaults.mak

# DSelect interfacing directory
SOURCE = desc.apt install names setup update
TO = $(BUILD)/dselect
include $(COPY_H)
	
