# -*- make -*-
BASE=../..
SUBDIR=doc/it

# Bring in the default rules
include ../../buildlib/defaults.mak

# Debian Doc SGML Documents
SOURCE = guide.it.sgml
DEBIANDOC_HTML_OPTIONS=-l it
include $(DEBIANDOC_H)
