#!/bin/sh
set -e

TESTDIR=$(readlink -f $(dirname $0))
. $TESTDIR/framework

setupenvironment
configarchitecture "i386"

insertpackage 'unstable' 'foo' 'all' '2.0'
cp rootdir/var/lib/dpkg/status dpkg.status
insertinstalledpackage 'foo' 'all' '1.0'

setupaptarchive --no-update

APTARCHIVE=$(readlink -f ./aptarchive)

testequal 'E: The update command takes no arguments' apt update -q arguments

testequal "1 package can be upgraded. Run 'apt list --upgradable' to see it." apt update -q

cp dpkg.status rootdir/var/lib/dpkg/status
insertinstalledpackage 'foo' 'all' '2.0'
testequal 'All packages are up to date.' apt update -q
