#!/bin/sh
#
# Regression test for debian bug #749795. Ensure that we fail with
# an error if apt-get source foo will download a source that comes
# from a unauthenticated repository
#
set -e

TESTDIR="$(readlink -f "$(dirname "$0")")"
. "$TESTDIR/framework"

setupenvironment
configarchitecture "i386"

# a "normal" package with source and binary
buildsimplenativepackage 'foo' 'all' '2.0'

setupaptarchive --no-update

APTARCHIVE="$(readlink -f ./aptarchive)"
find "$APTARCHIVE/dists/unstable" -name '*Release*' -delete

# update without authenticated InRelease file
testwarning aptget update --allow-insecure-repositories

# this all should fail
testfailure aptget install -y foo
cd downloaded
testfailure aptget source foo
testfailure test -e foo_2.0.dsc
# allow overriding the warning
testsuccess aptget source --allow-unauthenticated foo -o Debug::pkgAcquire::Worker=1
testsuccess test -s foo_2.0.dsc -a -L foo_2.0.dsc
