#!/bin/sh
set -e

TESTDIR="$(readlink -f "$(dirname "$0")")"
. "$TESTDIR/framework"
setupenvironment
configarchitecture 'native'

aptconfig dump --no-empty --format '%v%n' APT::Move-Autobit-Sections > move-autobit.sections
testsuccess grep '^oldlibs$' move-autobit.sections

buildsimplenativepackage 'libabc' 'native' '1' 'stable' '' '' 'libs'
buildsimplenativepackage 'libabc' 'native' '2' 'unstable' 'Depends: libdef' '' 'oldlibs'
buildsimplenativepackage 'libdef' 'native' '1' 'unstable' '' '' 'libs'
setupaptarchive

testmarkedauto
testmarkedmanual 'dpkg'

testsuccess aptget install libabc/stable -y
testdpkginstalled 'libabc'
testdpkgnotinstalled 'libdef'

testmarkedmanual 'dpkg' 'libabc'
testmarkedauto

testsuccess aptget dist-upgrade -y
testdpkginstalled 'libabc' 'libdef'

testmarkedauto 'libabc'
testmarkedmanual 'dpkg' 'libdef'
