#!/bin/sh
set -e

TESTDIR="$(readlink -f "$(dirname "$0")")"
. "$TESTDIR/framework"
setupenvironment
configarchitecture 'amd64'

insertpackage 'installed' 'avahi-daemon' 'all' '1' 'Suggests: avahi-autoipd'
insertpackage 'installed' 'dhcpd-base' 'all' '1' 'Provides: avahi-autoipd'
insertpackage 'unstable' 'avahi-autoipd' 'all'  2
insertpackage 'unstable' 'dhcpd-base' 'all' '2'

setupaptarchive

# It seems surprising this does not install avahi-autoipd
testsuccessequal "Reading package lists...
Building dependency tree...
Calculating upgrade...
The following packages will be upgraded:
  dhcpd-base
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Inst dhcpd-base [1] (2 unstable [all])
Conf dhcpd-base (2 unstable [all])" aptget upgrade -s -q --solver 3.0

# Or is it surprising that this does?
for command in "aptget dist-upgrade" "apt upgrade" "apt dist-upgrade"; do
testsuccessequal "Reading package lists...
Building dependency tree...
Calculating upgrade...
The following NEW packages will be installed:
  avahi-autoipd
The following packages will be upgraded:
  dhcpd-base
1 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Inst avahi-autoipd (2 unstable [all])
Inst dhcpd-base [1] (2 unstable [all])
Conf avahi-autoipd (2 unstable [all])
Conf dhcpd-base (2 unstable [all])" $command -s -q --solver 3.0
done

for command in "aptget upgrade" "aptget dist-upgrade" "apt upgrade" "apt dist-upgrade"; do
testsuccessequal "Reading package lists...
Building dependency tree...
Calculating upgrade...
The following packages will be upgraded:
  dhcpd-base
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Inst dhcpd-base [1] (2 unstable [all])
Conf dhcpd-base (2 unstable [all])" $command -s --solver internal -q
done

