#!/bin/sh
set -e

TESTDIR="$(readlink -f "$(dirname "$0")")"
. "$TESTDIR/framework"
setupenvironment
configarchitecture 'amd64' 'armel'

insertinstalledpackage 'build-essential' 'all' '11.5' 'Multi-Arch: foreign'

insertpackage 'unstable' 'po-debconf' 'all' '1'
insertsource 'unstable' 'dash' 'any' '1' 'Build-Depends: po-debconf'
insertpackage 'unstable' 'make-po-debconf-pure-virtual' 'armel' '1' 'Depends: po-debconf'

insertsource 'unstable' 'diffutils' 'any' '1' 'Build-Depends: texi2html'

insertpackage 'unstable' 'libselinux1-dev' 'amd64' '1' 'Provides: libselinux-dev'
insertsource 'unstable' 'sed' 'any' '1' 'Build-Depends: libselinux-dev'

insertpackage 'unstable' 'libsehurd1-dev' 'amd64,armel' '1' 'Provides: libsehurd-dev'
insertsource 'unstable' 'sed2' 'any' '1' 'Build-Depends: libsehurd-dev'

setupaptarchive

testsuccessequal 'Package: po-debconf:armel
Versions: 

Reverse Depends: 
  make-po-debconf-pure-virtual:armel,po-debconf:armel
Dependencies: 
Provides: 
Reverse Provides: ' aptcache showpkg po-debconf:armel
testsuccessequal 'N: Unable to locate package texi2html:armel' aptcache showpkg texi2html:armel

testsuccessequal 'Reading package lists...
Reading package lists...
Building dependency tree...
The following NEW packages will be installed:
  po-debconf
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Inst po-debconf (1 unstable [all])
Conf po-debconf (1 unstable [all])' aptget build-dep dash -s

testfailureequal 'Reading package lists...
Reading package lists...
Building dependency tree...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 builddeps:dash:armel : Depends: po-debconf:armel but it is not installable
E: Unable to correct problems, you have held broken packages.' aptget build-dep -aarmel dash -s
testfailureequal 'Reading package lists...
Reading package lists...
Building dependency tree...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 builddeps:diffutils:armel : Depends: texi2html:armel but it is not installable
E: Unable to correct problems, you have held broken packages.' aptget build-dep -aarmel diffutils -s

testsuccessequal "Reading package lists...
Reading package lists...
Building dependency tree...
The following NEW packages will be installed:
  libselinux1-dev
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Inst libselinux1-dev (1 unstable [amd64])
Conf libselinux1-dev (1 unstable [amd64])" aptget build-dep sed -s

testfailureequal 'Reading package lists...
Reading package lists...
Building dependency tree...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 builddeps:sed:armel : Depends: libselinux-dev:armel but it is not installable
E: Unable to correct problems, you have held broken packages.' aptget build-dep -aarmel sed -s

testsuccessequal "Reading package lists...
Reading package lists...
Building dependency tree...
The following NEW packages will be installed:
  libsehurd1-dev
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Inst libsehurd1-dev (1 unstable [amd64])
Conf libsehurd1-dev (1 unstable [amd64])" aptget build-dep sed2 -s

testsuccessequal "Reading package lists...
Reading package lists...
Building dependency tree...
The following NEW packages will be installed:
  libsehurd1-dev:armel
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Inst libsehurd1-dev:armel (1 unstable [armel])
Conf libsehurd1-dev:armel (1 unstable [armel])" aptget build-dep -aarmel sed2 -s
