#!/bin/sh
set -e

TESTDIR="$(readlink -f "$(dirname "$0")")"
. "$TESTDIR/framework"

setupenvironment
configarchitecture "i386"

insertpackage 'unstable' 'foo' 'all' '2.0' 'Depends: foo-new-dependency'
insertpackage 'unstable' 'foo-new-dependency' 'all' '2.0'
insertinstalledpackage 'foo' 'all' '1.0'

setupaptarchive

APTARCHIVE="$(readlink -f ./aptarchive)"

# default is to allow new dependencies
testsuccessequal "The following NEW packages will be installed:
  foo-new-dependency
The following packages will be upgraded:
  foo
1 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Inst foo-new-dependency (2.0 unstable [all])
Inst foo [1.0] (2.0 unstable [all])
Conf foo-new-dependency (2.0 unstable [all])
Conf foo (2.0 unstable [all])" apt upgrade -qq -s

# ensure the 'old' way works as well
testsuccessequal "The following packages have been kept back:
  foo
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded." apt upgrade -qq -s --no-new-pkgs
