#!/bin/sh
set -e

TESTDIR=$(readlink -f $(dirname $0))
. $TESTDIR/framework

setupenvironment
configarchitecture "i386"

buildsimplenativepackage 'apt' 'all' '1.0' 'stable'
buildsimplenativepackage 'apt' 'all' '2.0' 'unstable'

setupaptarchive

testdownload() {
	local APT="$2"
	if [ -n "$3" ]; then
		APT="${APT}/${3}"
	fi
	msgtest "Test download of package file $1 with" "$APT"
	aptget -qq download ${APT} && test -f $1 && msgpass || msgfail
}

testdownload apt_1.0_all.deb apt stable
testdownload apt_2.0_all.deb apt

DEBFILE="$(readlink -f aptarchive)/pool/apt_2.0_all.deb"
testequal "'file://${DEBFILE}' apt_2.0_all.deb $(stat -c%s $DEBFILE) sha256:$(sha256sum $DEBFILE | cut -d' ' -f 1)" aptget download apt --print-uris
