#!/bin/sh
set -e

TESTDIR=$(readlink -f $(dirname $0))
. $TESTDIR/framework

setupenvironment
configarchitecture 'i386'

changetohttpswebserver

test_apt_helper_download() {
    echo 'foo' > aptarchive/foo
    echo 'bar' > aptarchive/foo2

    msgtest 'apt-file download-file sha1'
    testsuccess --nomsg apthelper download-file http://localhost:8080/foo ./downloaded/foo1 SHA1:f1d2d2f924e986ac86fdf7b36c94bcdf32beec15
    testfileequal ./downloaded/foo1 'foo'

    msgtest 'apt-file download-file sha256'
    testsuccess --nomsg apthelper download-file http://localhost:8080/foo ./downloaded/foo3 SHA256:b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c
    testfileequal ./downloaded/foo3 'foo'

    msgtest 'apt-file download-file no-hash'
    testsuccess --nomsg apthelper download-file http://localhost:8080/foo ./downloaded/foo4
    testfileequal ./downloaded/foo4 'foo'
    
    msgtest 'apt-file download-file wrong hash'
    testfailure --nomsg apthelper -qq download-file http://localhost:8080/foo ./downloaded/foo5 SHA256:aabbcc
    testfileequal rootdir/tmp/testfailure.output 'E: Failed to fetch http://localhost:8080/foo  Hash Sum mismatch

E: Download Failed'
    testfileequal ./downloaded/foo5.FAILED 'foo'

    msgtest 'apt-file download-file sha256 sha1'
    testsuccess --nomsg apthelper download-file http://localhost:8080/foo ./downloaded/foo6 SHA256:b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c http://localhost:8080/foo2 ./downloaded/foo7 SHA1:e242ed3bffccdf271b7fbaf34ed72d089537b42f
    testfileequal ./downloaded/foo6 'foo'
    testfileequal ./downloaded/foo7 'bar'
}

test_apt_helper_detect_proxy() {
    # no proxy
    testsuccessequal "Using proxy '' for URL 'http://example.com/'" apthelper auto-detect-proxy http://example.com/


    # http auto detect proxy script
    cat > apt-proxy-detect <<'EOF'
#!/bin/sh -e
echo "http://some-proxy"
EOF
    chmod 755 apt-proxy-detect
    echo "Acquire::http::Proxy-Auto-Detect \"$(pwd)/apt-proxy-detect\";" > rootdir/etc/apt/apt.conf.d/02proxy-detect

    testsuccessequal "Using proxy 'http://some-proxy' for URL 'http://www.example.com/'" apthelper auto-detect-proxy http://www.example.com


    # https auto detect proxy script
    cat > apt-proxy-detect <<'EOF'
#!/bin/sh -e
echo "https://https-proxy"
EOF
    chmod 755 apt-proxy-detect
    echo "Acquire::https::Proxy-Auto-Detect \"$(pwd)/apt-proxy-detect\";" > rootdir/etc/apt/apt.conf.d/02proxy-detect

    testsuccessequal "Using proxy 'https://https-proxy' for URL 'https://ssl.example.com/'" apthelper auto-detect-proxy https://ssl.example.com
}

test_apt_helper_download
test_apt_helper_detect_proxy

# test failure modes
testfailureequal 'E: Invalid operation download' apthelper download
testfailureequal 'E: Must specify at least one pair url/filename' apthelper download-file
testfailureequal 'E: Must specify at least one pair url/filename' apthelper download-file http://example.org/
testfailureequal 'E: Need one URL as argument' apthelper auto-detect-proxy
