#!/bin/sh
set -e

TESTDIR=$(readlink -f $(dirname $0))
. $TESTDIR/framework
setupenvironment
configarchitecture 'amd64'

buildsimplenativepackage 'unrelated' 'all' '0.5~squeeze1' 'unstable'

setupaptarchive
changetowebserver -o aptwebserver::redirect::replace::/pool/=/newpool/ \
		  -o aptwebserver::redirect::replace::/dists/=/newdists/

mv aptarchive/pool aptarchive/newpool
mv aptarchive/dists aptarchive/newdists

msgtest 'Test redirection works in' 'apt-get update'
aptget update -qq && msgpass || msgfail

# check that I-M-S header is kept in redirections
testequal 'Hit http://localhost unstable Release.gpg
Hit http://localhost unstable Release
Hit http://localhost unstable/main Sources
Hit http://localhost unstable/main amd64 Packages
Hit http://localhost unstable/main Translation-en
Reading package lists...' aptget update

msgtest 'Test redirection works in' 'package download'
aptget install unrelated --download-only -qq && msgpass || msgfail
