#!/bin/sh
set -e

TESTDIR="$(readlink -f "$(dirname "$0")")"
. "$TESTDIR/framework"
setupenvironment
configarchitecture "i386"
setupaptarchive

testfailuremsg "E: Conflict: exim4-daemon-light:i386 -> exim4-daemon-light:i386=4.72-1 -> not postfix:i386=2.7.1-1 but postfix:i386=2.7.1-1" aptget install postfix --solver 3.0
allowremovemanual
testfailureequal "Reading package lists...
Building dependency tree...
The following packages will be REMOVED:
  exim4 exim4-daemon-light
The following NEW packages will be installed:
  postfix
0 upgraded, 1 newly installed, 2 to remove and 0 not upgraded.
Need to get 0 B/1326 kB of archives.
After this operation, 2236 kB of additional disk space will be used.
E: Trivial Only specified but this is not a trivial operation." aptget install postfix --trivial-only
