#!/bin/sh
set -e

TESTDIR=$(readlink -f $(dirname $0))
. $TESTDIR/framework
setupenvironment
configarchitecture "i386"

insertinstalledpackage 'libc-bin' 'i386' '2.13-8' 'Replaces: libc6'
insertpackage 'unstable' 'libc-bin' 'i386' '2.13-8' 'Replaces: libc6'
insertinstalledpackage 'libc6' 'i386' '2.13-8' 'Depends: libc-bin (= 2.13-8)'
insertpackage 'unstable' 'libc6' 'i386' '2.13-8' 'Depends: libc-bin (= 2.13-8)'
insertinstalledpackage 'apt' 'i386' '0.8.15' 'Depends: libc6'

setupaptarchive

aptget install --reinstall libc6 libc-bin -s -o Debug::pkgPackageManager=1
