#!/bin/sh
set -e

TESTDIR=$(readlink -f $(dirname $0))
. $TESTDIR/framework
setupenvironment
configarchitecture 'amd64' 'armel'

insertinstalledpackage 'build-essential' 'all' '11.5' 'Multi-Arch: foreign'

insertpackage 'unstable' 'po-debconf' 'all' '1'
insertsource 'unstable' 'dash' 'any' '1' 'Build-Depends: po-debconf'
insertpackage 'unstable' 'make-po-debconf-pure-virtual' 'armel' '1' 'Depends: po-debconf'

insertpackage 'unstable' 'po-debconf' 'amd64' '1'
insertsource 'unstable' 'diffutils' 'any' '1' 'Build-Depends: texi2html'

insertpackage 'unstable' 'libselinux1-dev' 'amd64' '1' 'Provides: libselinux-dev'
insertsource 'unstable' 'sed' 'any' '1' 'Build-Depends: libselinux-dev'

insertpackage 'unstable' 'libsehurd1-dev' 'amd64,armel' '1' 'Provides: libsehurd-dev'
insertsource 'unstable' 'sed2' 'any' '1' 'Build-Depends: libsehurd-dev'

setupaptarchive

testequal 'Package: po-debconf:armel
Versions: 

Reverse Depends: 
  make-po-debconf-pure-virtual:armel,po-debconf:armel
Dependencies: 
Provides: 
Reverse Provides: ' aptcache showpkg po-debconf:armel
testequal 'N: Unable to locate package texi2html' aptcache showpkg texi2html:armel -q=0

testequal 'Reading package lists...
Building dependency tree...
The following NEW packages will be installed:
  po-debconf
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Inst po-debconf (1 unstable, unstable [all])
Conf po-debconf (1 unstable, unstable [all])' aptget build-dep dash -s

testequal 'Reading package lists...
Building dependency tree...
E: Build-Depends dependency for dash cannot be satisfied because the package po-debconf cannot be found' aptget build-dep -aarmel dash -s

testequal 'Reading package lists...
Building dependency tree...
E: Build-Depends dependency for diffutils cannot be satisfied because the package texi2html cannot be found' aptget build-dep -aarmel diffutils -s

testequal "Reading package lists...
Building dependency tree...
Note, selecting 'libselinux1-dev' instead of 'libselinux-dev'
The following NEW packages will be installed:
  libselinux1-dev
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Inst libselinux1-dev (1 unstable [amd64])
Conf libselinux1-dev (1 unstable [amd64])" aptget build-dep sed -s

testequal 'Reading package lists...
Building dependency tree...
E: Build-Depends dependency for sed cannot be satisfied because the package libselinux-dev cannot be found' aptget build-dep -aarmel sed -s

testequal "Reading package lists...
Building dependency tree...
Note, selecting 'libsehurd1-dev' instead of 'libsehurd-dev'
The following NEW packages will be installed:
  libsehurd1-dev
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Inst libsehurd1-dev (1 unstable [amd64])
Conf libsehurd1-dev (1 unstable [amd64])" aptget build-dep sed2 -s

testequal "Reading package lists...
Building dependency tree...
Note, selecting 'libsehurd1-dev:armel' instead of 'libsehurd-dev:armel'
The following NEW packages will be installed:
  libsehurd1-dev:armel
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Inst libsehurd1-dev:armel (1 unstable [armel])
Conf libsehurd1-dev:armel (1 unstable [armel])" aptget build-dep -aarmel sed2 -s
