#!/bin/sh
set -e

TESTDIR=$(readlink -f $(dirname $0))
. $TESTDIR/framework

setupenvironment
configarchitecture 'amd64' 'i386'

buildsimplenativepackage 'testing' 'amd64' '0.1' 'stable'
buildsimplenativepackage 'testing' 'amd64' '0.8.15' 'stable'
buildsimplenativepackage 'testing2' 'amd64,i386' '0.8.15' 'stable'
setupaptarchive 

# install native
exec 3> apt-progress.log
testsuccess aptget install testing=0.1 -y -o APT::Status-Fd=3
testequal "dlstatus:1:0:Retrieving file 1 of 1
dlstatus:1:0:Retrieving file 1 of 1
pmstatus:dpkg-exec:0:Running dpkg
pmstatus:testing:0:Installing testing (amd64)
pmstatus:testing:20:Preparing testing (amd64)
pmstatus:testing:40:Unpacking testing (amd64)
pmstatus:testing:60:Preparing to configure testing (amd64)
pmstatus:dpkg-exec:60:Running dpkg
pmstatus:testing:60:Configuring testing (amd64)
pmstatus:testing:80:Configuring testing (amd64)
pmstatus:testing:100:Installed testing (amd64)" cat apt-progress.log

# upgrade
exec 3> apt-progress.log
testsuccess aptget install testing=0.8.15 -y -o APT::Status-Fd=3
testequal "dlstatus:1:0:Retrieving file 1 of 1
dlstatus:1:0:Retrieving file 1 of 1
pmstatus:dpkg-exec:0:Running dpkg
pmstatus:testing:20:Preparing testing (amd64)
pmstatus:testing:40:Unpacking testing (amd64)
pmstatus:testing:60:Preparing to configure testing (amd64)
pmstatus:dpkg-exec:60:Running dpkg
pmstatus:testing:60:Configuring testing (amd64)
pmstatus:testing:80:Configuring testing (amd64)
pmstatus:testing:100:Installed testing (amd64)" cat apt-progress.log

# and remove
exec 3> apt-progress.log
testsuccess aptget remove testing -y -o APT::Status-Fd=3
testequal "pmstatus:dpkg-exec:0:Running dpkg
pmstatus:testing:0:Removing testing (amd64)
pmstatus:testing:33.3333:Preparing for removal of testing (amd64)
pmstatus:testing:66.6667:Removing testing (amd64)
pmstatus:testing:100:Removed testing (amd64)" cat apt-progress.log

# install non-native and ensure we get proper progress info
exec 3> apt-progress.log
testsuccess aptget install testing2:i386 -y -o APT::Status-Fd=3

# and compare
testequal "dlstatus:1:0:Retrieving file 1 of 1
dlstatus:1:0:Retrieving file 1 of 1
pmstatus:dpkg-exec:0:Running dpkg
pmstatus:testing2:0:Installing testing2 (i386)
pmstatus:testing2:20:Preparing testing2 (i386)
pmstatus:testing2:40:Unpacking testing2 (i386)
pmstatus:testing2:60:Preparing to configure testing2 (i386)
pmstatus:dpkg-exec:60:Running dpkg
pmstatus:testing2:60:Configuring testing2 (i386)
pmstatus:testing2:80:Configuring testing2 (i386)
pmstatus:testing2:100:Installed testing2 (i386)" cat apt-progress.log

rm -f apt-progress*.log
