#!/bin/sh
set -e

TESTDIR=$(readlink -f $(dirname $0))
. $TESTDIR/framework

setupenvironment
configarchitecture "i386"

buildsimplenativepackage 'apt' 'all' '1.0' 'stable'
setupaptarchive --no-update

changetohttpswebserver  -o 'aptwebserver::redirect::replace::/redirectme/=http://localhost:8080/'

DOWNLOG='download-testfile.log'
msgtest 'normal http download works'
downloadfile 'http://localhost:8080/pool/apt_1.0/changelog' changelog2 > "$DOWNLOG" && msgpass || msgfail

msgtest 'normal https download works'
downloadfile 'https://localhost:4433/pool/apt_1.0/changelog' changelog > "$DOWNLOG" && msgpass || msgfail

msgtest 'redirecting https to http does not work'
if ! downloadfile 'https://localhost:4433/redirectme/pool/apt_1.0/changelog' changelog3 > "$DOWNLOG"; then
    msgpass
else
    cat >&2 "$DOWNLOG"
    msgfail
fi
    
msgtest 'https methods given proper error on redirect attempt'
if grep -q 'Protocol http not supported or disabled in libcurl' "$DOWNLOG"; then
    msgpass
else
    cat >&2 "$DOWNLOG"
    msgfail
fi


