#!/bin/sh
set -e

TESTDIR="$(readlink -f "$(dirname "$0")")"
. "$TESTDIR/framework"
setupenvironment
configarchitecture 'native'

insertpackage 'unstable' 'foobar' 'native' '1' '' '' 'funky tool'
insertpackage 'unstable' 'coolstuff' 'native' '1' '' '' 'funky tool just like foo and bar'
insertpackage 'unstable' 'foo' 'native' '1' '' '' 'tool best used with bar'
insertpackage 'unstable' 'bar' 'native' '1' '' '' 'tool best used with foo'
insertpackage 'unstable' 'baz' 'native' '1' 'Provides: bar' '' 'alternative tool best used with foo'

setupaptarchive

# in this special case the following queries should be equal
FOOBAR='foobar - funky tool
coolstuff - funky tool just like foo and bar
foo - tool best used with bar
bar - tool best used with foo
baz - alternative tool best used with foo'

testsuccessequal "$FOOBAR" aptcache search foo
testsuccessequal "$FOOBAR" aptcache search bar
testsuccessequal "$FOOBAR" aptcache search foo bar

testsuccessequal 'foobar - funky tool
foo - tool best used with bar' aptcache search -n foo
testsuccessequal 'foobar - funky tool
bar - tool best used with foo
baz - alternative tool best used with foo' aptcache search -n bar
testsuccessequal 'foobar - funky tool' aptcache search -n foo bar
