#!/bin/sh
set -e

TESTDIR="$(readlink -f "$(dirname "$0")")"
. "$TESTDIR/framework"
setupenvironment
configarchitecture "i386"

insertpackage 'unstable' 'libc6' 'all' '1.0'
insertpackage 'unstable' 'coolstuff' 'all' '1.0' 'Recommends: extracoolstuff'
insertpackage 'unstable' 'extracoolstuff' 'all' '1.0' 'Depends: libc6'

setupaptarchive

# We check the Markers here as the autoremove nuker will also
# prevent it, but to late - its better to fail earlier
testsuccessequal "Reading package lists...
Building dependency tree...
  MarkInstall coolstuff:i386 < none -> 1.0 @un puN IPb > FU=1
    coolstuff:i386 Recommends on extracoolstuff:i386 < none | 1.0 @hn puH > can't be satisfied! (dep)
Package 'extracoolstuff' is not installed, so not removed
Recommended packages:
  extracoolstuff
The following NEW packages will be installed:
  coolstuff
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Inst coolstuff (1.0 unstable [all])
Conf coolstuff (1.0 unstable [all])" aptget install coolstuff extracoolstuff- -o Debug::pkgDepCache::Marker=1 -s
