#!/bin/sh
set -e

TESTDIR="$(readlink -f "$(dirname "$0")")"
. "$TESTDIR/framework"
setupenvironment
configarchitecture 'amd64' 'i386'

buildsimplenativepackage 'pkgall' 'all' '1' 'stable'
buildsimplenativepackage 'pkgnative' 'amd64' '1' 'stable'
buildsimplenativepackage 'pkgforeign' 'i386' '1' 'stable'

setupaptarchive

changetowebserver

testsuccess aptget update
testsuccess aptget install pkgall pkgnative pkgforeign -y

# if we work with an old dpkg, pkgforeign will be listed differently,
# so test with aptcache for install status instead
testdpkginstalled pkgall pkgnative
testsuccess aptcache show pkgforeign/installed

testsuccessequal 'Reading package lists...
Building dependency tree...
Reading state information...' aptget autoclean -s
