#!/bin/sh

set -e

TESTDIR=$(readlink -f $(dirname $0))
. $TESTDIR/framework
setupenvironment
configarchitecture 'i386'

buildsimplenativepackage 'coolstuff' 'all' '1.0' 'unstable'

setupaptarchive
changetowebserver

msgtest 'Test with incorect TMPDIR'
export TMPDIR=/does-not-exists
aptget update && msgpass || msgfail
unset TMPDIR