#!/bin/sh
set -e

TESTDIR="$(readlink -f "$(dirname "$0")")"
. "$TESTDIR/framework"
setupenvironment
configarchitecture "i386"
setupaptarchive

# FIXME: Should this say selected postifx?
testfailuremsg "E: Unable to satisfy dependencies. Reached two conflicting decisions:
   1. postfix:i386=2.7.1-1 is selected for install
   2. postfix:i386=2.7.1-1 is not selected for install because:
      1. exim4-daemon-light:i386 is selected for install
      2. exim4-daemon-light:i386 Conflicts mail-transport-agent
         [selected exim4-daemon-light:i386]" aptget install postfix --solver 3.0
allowremovemanual
testfailureequal "Reading package lists...
Building dependency tree...
The following packages will be REMOVED:
  exim4 exim4-daemon-light
The following NEW packages will be installed:
  postfix
0 upgraded, 1 newly installed, 2 to remove and 0 not upgraded.
Need to get 0 B/1326 kB of archives.
After this operation, 2236 kB of additional disk space will be used.
E: Trivial Only specified but this is not a trivial operation." aptget install postfix --trivial-only
