#!/bin/sh
set -e

TESTDIR=$(readlink -f $(dirname $0))
. $TESTDIR/framework
setupenvironment
configarchitecture 'i386'

cat > rootdir/etc/apt/preferences <<EOF
Package: *
Pin: release testing
Pin-Priority: 600

Package: *
Pin: release unstable
Pin-Priority: 1
EOF

insertinstalledpackage 'foo' 'all' '1'
insertpackage 'testing' 'foo' 'all' '1'
insertpackage 'testing-updates' 'foo' 'all' '2'
insertpackage 'unstable' 'foo' 'all' '3'

insertinstalledpackage 'bar' 'all' '1'
insertpackage 'testing' 'bar' 'all' '2'

setupaptarchive

testequal "Listing...
bar/testing 2 all [upgradable from: 1]" apt list --upgradable

testequal "Listing...
bar/testing 2 all [upgradable from: 1]
foo/testing,now 1 all [installed]" apt list
