#!/bin/sh
set -e

TESTDIR="$(readlink -f "$(dirname "$0")")"
. "$TESTDIR/framework"

setupenvironment
configarchitecture 'i386'


insertpackage 'stable' 'build-depends' 'i386' '1'
insertpackage 'stable' 'foo' 'i386' '1'
insertinstalledpackage 'build-essential' 'i386' '1'

setupaptarchive

# This used to be interpreted as build-depends | foo
cat > foobar.dsc <<EOF
Format: 3.0 (native)
Source: foobar
Binary: foobar
Architecture: all
Version: 1
Maintainer: Joe Sixpack <joe@example.org>
Build-Depends: build-depends [i386] | build-depends [amd64], foo
Standards-Version: 3.9.8
EOF
testsuccessequal "Note, using file './foobar.dsc' to get the build dependencies
Reading package lists...
Building dependency tree...
The following NEW packages will be installed:
  build-depends foo
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Inst build-depends (1 stable [i386])
Inst foo (1 stable [i386])
Conf build-depends (1 stable [i386])
Conf foo (1 stable [i386])" aptget build-dep --simulate ./foobar.dsc


# This caused a segmentation fault
cat > foobar.dsc <<EOF
Format: 3.0 (native)
Source: foobar
Binary: foobar
Architecture: all
Version: 1
Maintainer: Joe Sixpack <joe@example.org>
Build-Depends: build-depends [i386] | build-depends [amd64]
Standards-Version: 3.9.8
EOF
testsuccessequal "Note, using file './foobar.dsc' to get the build dependencies
Reading package lists...
Building dependency tree...
The following NEW packages will be installed:
  build-depends
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Inst build-depends (1 stable [i386])
Conf build-depends (1 stable [i386])" aptget build-dep --simulate ./foobar.dsc
