#!/bin/sh
set -e

TESTDIR="$(readlink -f "$(dirname "$0")")"
. "$TESTDIR/framework"

setupenvironment
configarchitecture "i386"

# try a little harder to create a size mismatch
buildsimplenativepackage 'pkg0' 'all' '1.0' 'stable' "Depends: foo" '' '' '' '' 'none'
buildsimplenativepackage 'pkga' 'all' '1.0' 'stable' "Depends: foo" '' '' '' '' 'none'
buildsimplenativepackage 'pkgb' 'all' '1.0' 'stable' "Depends: foo" '' '' '' '' 'none'
buildsimplenativepackage 'pkgc' 'all' '1.0' 'stable' "Depends: f$(for i in $(seq 0 1000); do printf 'o'; done)" '' '' '' '' 'none'
buildsimplenativepackage 'pkgd' 'all' '1.0' 'stable' "Depends: f$(for i in $(seq 0 1000); do printf 'o'; done)" '' '' '' '' 'none'

setupaptarchive --no-update

# simulate (and be a predictable) pipeline mess-up by the server/proxy
changetowebserver \
	-o 'aptwebserver::overwrite::.*pkga.*::filename=/pool/pkgd_1.0_all.deb' \
	-o 'aptwebserver::overwrite::.*pkgc.*::filename=/pool/pkgb_1.0_all.deb' \
	-o 'aptwebserver::overwrite::.*pkgb.*::filename=/pool/pkgc_1.0_all.deb' \
	-o 'aptwebserver::overwrite::.*pkgd.*::filename=/pool/pkga_1.0_all.deb'

echo 'Debug::Acquire::http "true";
Debug::pkgAcquire::Worker "true";' > rootdir/etc/apt/apt.conf.d/99debug

testsuccess aptget update

cd downloaded
# messup is bigger than pipeline: checks if fixup isn't trying too hard
testfailure aptget download pkga pkgb pkgc pkgd -o Acquire::http::Pipeline-Depth=2
for pkg in 'pkga' 'pkgd'; do
	testfailure test -f ${pkg}_1.0_all.deb
done
for pkg in 'pkgb' 'pkgc'; do
	testsuccess test -f ${pkg}_1.0_all.deb
	testsuccess cmp ../incoming/${pkg}_1.0_all.deb ${pkg}_1.0_all.deb
	rm -f ${pkg}_1.0_all.deb
done

# ensure that pipeling is enabled for rest of this test
echo 'Acquire::http::Pipeline-Depth 10;' > ../rootdir/etc/apt/apt.conf.d/99enable-pipeline

# the output is a bit strange: it looks like it has downloaded pkga 4 times
testwarning aptget download pkg0 pkga pkgb pkgc pkgd
for pkg in 'pkg0' 'pkga' 'pkgb' 'pkgc' 'pkgd'; do
	testsuccess test -f ${pkg}_1.0_all.deb
	testsuccess cmp ../incoming/${pkg}_1.0_all.deb ${pkg}_1.0_all.deb
	rm -f ${pkg}_1.0_all.deb
done

# while hashes will pass (as none are available), sizes will not match, so failure
# checks that no hashes means that pipeline depth is ignored as we can't fixup
testfailure aptget download pkga pkgb pkgc pkgd --allow-unauthenticated -o Acquire::ForceHash=ROT26
