#!/bin/sh
set -e

TESTDIR="$(readlink -f "$(dirname "$0")")"
. "$TESTDIR/framework"
setupenvironment
configarchitecture 'amd64' 'i386' 'armel'

buildsimplenativepackage 'libsame' 'amd64,i386,armel' '1.0' 'unstable' 'Multi-Arch: same'

setupaptarchive

testsuccess aptget install libsame libsame:i386

REINSTALL='Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 2 reinstalled, 0 to remove and 0 not upgraded.
Inst libsame [1.0] (1.0 unstable [amd64])
Inst libsame:i386 [1.0] (1.0 unstable [i386])
Conf libsame (1.0 unstable [amd64])
Conf libsame:i386 (1.0 unstable [i386])'

testsuccessequal "$REINSTALL" aptget install --reinstall libsame -s
testsuccessequal "$REINSTALL" aptget install --reinstall libsame:amd64 -s
testsuccessequal "$REINSTALL" aptget install --reinstall libsame:i386 -s
testsuccessequal "$REINSTALL" aptget install --reinstall libsame:amd64 libsame:i386 -s
