#!/bin/sh
set -e

TESTDIR=$(readlink -f $(dirname $0))
. $TESTDIR/framework

setupenvironment
configarchitecture 'amd64'

insertpackage 'testing' 'foo' 'all' '1'
insertpackage 'unstable' 'foo' 'all' '2'
insertinstalledpackage 'foo' 'all' '3'

setupaptarchive

# nothing to do always works
testsuccess aptget clean

# generate some dirt and clean it up
touch rootdir/var/lib/apt/lists/partial/http.debian.net_debian_dists_sid_main_i18n_Translation-en
touch rootdir/var/cache/apt/archives/foo_1_all.deb
touch rootdir/var/cache/apt/archives/foo_2_all.deb
touch rootdir/var/cache/apt/archives/foo_3_all.deb
touch rootdir/var/cache/apt/archives/foo_4_all.deb

testsuccess aptget clean

testsuccess test ! -e rootdir/var/lib/apt/lists/partial/http.debian.net_debian_dists_sid_main_i18n_Translation-en
testsuccess test ! -e rootdir/var/cache/apt/archives/foo_1_all.deb
testsuccess test ! -e rootdir/var/cache/apt/archives/foo_2_all.deb
testsuccess test ! -e rootdir/var/cache/apt/archives/foo_3_all.deb
testsuccess test ! -e rootdir/var/cache/apt/archives/foo_4_all.deb


