# -*- make -*-
BASE=../..
SUBDIR=doc/ja

# Bring in the default rules
include ../../buildlib/defaults.mak

# Man pages
SOURCE = apt-cache.ja.8 apt-get.ja.8 apt-cdrom.ja.8 apt.conf.ja.5
INCLUDES = apt.ent.ja
include $(SGML_MANPAGE_H)
